### ISSUE TITLE
Remove duplicate providers in aggregated result

### ISSUE THREAD

**Issue by masih** [filecoin-shipyard/indexstar#31]
Results return by reframe aggregation logic [filter out duplicates by provider ID](https://github.com/filecoin-shipyard/indexstar/blob/main/reframe.go#L115). But [HTTP find](https://github.com/filecoin-shipyard/indexstar/blob/main/find.go#L104) and [reframe translator](https://github.com/filecoin-shipyard/indexstar/blob/main/reframe_translator.go#L84) do not do such filtering.

Ideally, the response should not include duplicate provider information.

**Comment by willscott** [comment]
Duplicate records are removed https://github.com/filecoin-shipyard/indexstar/blob/main/find.go#L115-L117 at a reasonable level for HTTP find.

the 'duplicates' we see there all have distinct context id's

**Comment by masih** [comment]
I see thank you for pointing that out. For HTTP find am I right to say it's the uniqueness of metadata that matters? If so would it make sense to deduplicate based on address+metadata combination?

**Comment by willscott** [comment]
i think that's a semantic that's up to us to define.

The current semantics give us some useful visibility into what's being published by providers and lets us go back and figure out why provider implementations aren't cleaning up context IDs well.

if we only choose one of the context ids with identical metadata, do you think the providers would get confused that some provided record isn't shown in results?
